### ISSUE TITLE
CNI networking: Antrea

### ISSUE THREAD

**Issue by jbeda** [vmware-tanzu/tgik#326]
Monday or Tuesday:
* [x] Pick a topic and create/use an issue in the repo
* [x] If applicable coordinate with an upstream project if they're interested in attending the show
* [x] Create the graphic
* [x] Schedule on Youtube
* [x] Add scheduled episode to TGIK playlist on YT
* [x] Create short link in rebrandly
* [x] Tweet about it from your personal account
  * [x] Post tweets on internal #tgik slack channel and cc @castrojo and Vykky

Before episode:
* [x] Create HackMD page for live notes.  Start with README template in this repo
* [x] Paste HackMD URL on internal #tgik channel and cc @castrojo or other assistant
  * [ ] Assistant adds ~5-10 news items from around the web as possible "News of the Week"
* [x] Get everything tested well before episode so you can debug
* [x] Use internal slack channel to ensure that AV setup is good

After show (ideally right away but can wait until Monday):
* Create/submit PR for this repo
  * [x] Episode directory and README from hackmd
  * [x] Any other files from the episode that might be useful
  * [x] Update playlist.md with episode
  * Feel free to self merge
* [ ] Edit YT description to point to episode directory here
* [ ] OBS/OS Upgrade if applicable (Never on the day of a show)

**Comment by jayunit100** [comment]
Hiya joe, so,  for me learning antrea is mostly about comparing it with calico.

- Calico uses BGP, so nodes are routable.  Antrea uses OVS.  Sot the first most interesting thing is to run `route -n` on an antrea node, and notice that there are these "gateways", each with a `x.y.z.1` IP address:

```
# route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         172.17.0.1      0.0.0.0         UG    0      0        0 br-phy
10.10.0.0       0.0.0.0         255.255.255.0   U     0      0        0 antrea-gw0
10.10.1.0       10.10.1.1       255.255.255.0   UG    0      0        0 antrea-gw0
10.10.2.0       10.10.2.1       255.255.255.0   UG    0      0        0 antrea-gw0
172.17.0.0      0.0.0.0         255.255.0.0     U     0      0        0 br-phy
```


- Now you won't see that in calico ! thats because theres NO SWITCH in calico, and the nodes just broadcast routing information to each other about pods... So the next thing i think to do is spin up **prometheus** this is REALLY easy , you just git clone antrea, and run `kubectl apply -f build/yamls/antrea-prometheus.yml` NOTE YOU HAVE TO ENABLE PROMETHEUS METRICS IN THE ANTREA CONFIGMAP IN KUBESYSTEM when doing this.  Then of course just expose the master IP to prometheus however you want to.   You can then look at the tables for OVS and see what happens when you scale a deployment , to the number of OVS routing tables.

-  FINALLY i guess antctl is the next most obvious thing to play with, where you can see network policies.  My fave why to see this is run an nginx daemonset/networkpocliy combo, i.e.e 


```
➜  kind git:(master) ✗ cat nginx.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-ds
spec:
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: nginx
        image: nginx
➜  kind git:(master) ✗ cat pol.yaml
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: web-deny-all
spec:
  podSelector:
    matchLabels:
      app: web
  ingress: []
```

andd then use antctl and 
```
/tmp » kubectl -n kube-system exec -it antrea-agent-2kksz ovs-ofctl dump-flows br-int | grep table=90                 
``` 

to see how the new `conj` rules are created to track the firewalls.  This is different from calico bc in calico, the equivalent command woudl be to use `iptables-save` (and diff before/after policy applied) to see the iptables rules created to implement network policies.

Anyways, full summary is here https://github.com/jayunit100/k8sprototypes/blob/master/2020kubecon/cni_debugging.md and the metrics stuff is here https://github.com/jayunit100/k8sprototypes/tree/master/antrea_metrics !
